# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/first_zynq_syste/first_zynq_syste.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==first_zynq_syste || ORIG_REF_NAME==first_zynq_syste} -quiet] -quiet

# IP: bd/first_zynq_syste/ip/first_zynq_syste_processing_system7_0_0/first_zynq_syste_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==first_zynq_syste_processing_system7_0_0 || ORIG_REF_NAME==first_zynq_syste_processing_system7_0_0} -quiet] -quiet

# IP: bd/first_zynq_syste/ip/first_zynq_syste_axi_gpio_0_0/first_zynq_syste_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==first_zynq_syste_axi_gpio_0_0 || ORIG_REF_NAME==first_zynq_syste_axi_gpio_0_0} -quiet] -quiet

# IP: bd/first_zynq_syste/ip/first_zynq_syste_ps7_0_axi_periph_0/first_zynq_syste_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==first_zynq_syste_ps7_0_axi_periph_0 || ORIG_REF_NAME==first_zynq_syste_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/first_zynq_syste/ip/first_zynq_syste_rst_ps7_0_50M_0/first_zynq_syste_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==first_zynq_syste_rst_ps7_0_50M_0 || ORIG_REF_NAME==first_zynq_syste_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/first_zynq_syste/ip/first_zynq_syste_auto_pc_0/first_zynq_syste_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==first_zynq_syste_auto_pc_0 || ORIG_REF_NAME==first_zynq_syste_auto_pc_0} -quiet] -quiet

# XDC: bd/first_zynq_syste/first_zynq_syste_ooc.xdc
